language: node_js
node_js:
   - "12.*"

branches:
  only:
    - master

before_script:
  - npm run build

after_success:
  - npm run cov-report
  - npm run cov-submit

notifications:
  email: false

sudo: false
