name: test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ dev ]

permissions:
  contents: read

jobs:
  build:

    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Local Unit Test ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Generate coverage report
        if: ${{ success() && github.event_name != 'pull_request' && matrix.node-version == '19.x' }}
        run: npm run cov-report
      - name: Coveralls
        if: ${{ success() && github.event_name != 'pull_request' && matrix.node-version == '19.x' }}
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
